sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rashid632/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rashid632/react-test npm test

after_success:
  - docker build -t rashid632/multi-client ./client
  - docker build -t rashid632/multi-nginx ./nginx
  - docker build -t rashid632/multi-server ./server
  - docker build -t rashid632/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rashid632/multi-client
  - docker push rashid632/multi-nginx
  - docker push rashid632/multi-server
  - docker push rashid632/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-869267742749'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
